
#შექმენით სია, სადაც დაამატებთ 5 ელემენტს, შემდეგ კი გამოიტანე მესამე და მეოთხე ელემენტები

SIA = ["TOMATO" , "APPLE" , "GOA" , "FRIEND" , "FLOUWER"]
SIA.append("beni")
SIA.append("cherry")

SIA.append("watermelon")
SIA.append("AXE")
SIA.append("winter")
print(SIA[3])
print(SIA[4])

#შექმენით სია, სადაც დაამატებთ 5 ელემენტს, შემდეგ მომხმარებელს შემოატანინეთ რიცხვი და რომელ რიცხსაც შემოიტანთ მისი ინდექსი დაპრინტეთ